### ISSUE TITLE
[Question] Terralith + BYG & Other Biomes Compatibility

### ISSUE THREAD

**Issue by ardissaps** [jakeb072001/TerraCraft#1]
Does it supposed to be compatible with other biomes? Such as BYG, Terralith, Incendium, BetterNether, BetterEnd thx in advance.

**Comment by jakeb072001** [comment]
My mod uses Terrablender to add the biomes, I believe BYG also uses Terrablender so they should be compatible. As far as I know it should also be compatible with the other mods you listed. If something is broken with my mod and one of those mods then it's most likely up to the Terrablender devs to fix the issue.
