### ISSUE TITLE
Game crashes on world load

### ISSUE THREAD

**Issue by Punkin-GH** [jakeb072001/TerraCraft#12]
**Describe the bug**

Game crashes on world load
Crash report: Accessed server level too early!

**To Reproduce**

1. Launch the game
2. Create or load a world
3. See error

**Game Environment**

 - Minecraft: 1.19.2
 - Quilt Loader: 0.18.1-beta.23
 - Quilted Fabric API: 4.0.0-beta.24+0.68.0-1.19.2
 - Cloth Config: 9.0.93
 - TerraBlender: 2.0.1.130
 - TerraMine: 1.6.0+1.19
 - Trinkets: 3.4.1
 - Architectury: 6.4.62

[latest.log](https://github.com/jakeb072001/TerraMine/files/10201319/latest.log)
[crash-2022-12-10_19.41.15-client.txt](https://github.com/jakeb072001/TerraMine/files/10201320/crash-2022-12-10_19.41.15-client.txt)

**Comment by jakeb072001** [comment]
Should be fixed with latest commit

**Comment by Punkin-GH** [comment]
Has the fix been released? The public available file (From Oct. 22) still has the same error.

**Comment by jakeb072001** [comment]
No, not yet, been way too busy this month to finish off the next update. If you want the fix early you can download the latest artifact from the Actions tab.

https://github.com/jakeb072001/TerraMine/actions/runs/3668934452 is for 1.19.2 which may be backwards compatible with 1.19 but haven't tested yet.

**Comment by Punkin-GH** [comment]
By luck, I happen to be running 1.19.2. Thanks for letting me know where to get the build!

**Comment by ItsIgnacioPortal** [comment]
The artifact expired, I can't download it :(
Please make a new release that contains this fix 🙏

**Comment by jakeb072001** [comment]
I have been slowly working on an update, but I got a job later last year so I have been very busy. I can probably compile the current jar and just upload it to this issue, that way it shouldn't expire.

**Comment by ItsIgnacioPortal** [comment]
> I have been slowly working on an update, but I got a job later last year so I have been very busy. I can probably compile the current jar and just upload it to this issue, that way it shouldn't expire.

that'd be great 😀

**Comment by ItsIgnacioPortal** [comment]
Nevermind, I made a fork of this repository and triggered the _build_ github action manually.

Here's the artifact: https://github.com/ItsIgnacioPortal/TerraMine/suites/11647249939/artifacts/604804413
Mirror: https://mega.nz/file/8t4XXb7Q#8Hc-loKTGu1fUU2bA_ap5tGKFx3Y4Ba126IE1KUTN6k

thanks for making such a cool mod @jakeb072001 😁
