### ISSUE TITLE
Crashing server when opening shadow chest

### ISSUE THREAD

**Issue by nihloheden** [jakeb072001/TerraCraft#15]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 2024-01-13 08:11:11
Description: Exception in server tick loop

java.lang.NoSuchFieldError: backgroundPainter
	at io.github.cottonmc.cotton.gui.widget.WPanel.<init>(WPanel.java:27)
	at io.github.cottonmc.cotton.gui.widget.WPanelWithInsets.<init>(WPanelWithInsets.java:12)
	at io.github.cottonmc.cotton.gui.widget.WGridPanel.<init>(WGridPanel.java:33)
	at io.github.cottonmc.cotton.gui.SyncedGuiDescription.<init>(SyncedGuiDescription.java:53)
	at net.minecraft.class_4970$class_4971.meth	at terramine.client.render.gui.menu.ChestBlockContainerMenu.<init>(ChestBlockContainerMenu.java:16)
	at terramine.common.entity.block.ChestEntity.createMenu(ChestEntity.java:79)
	at net.minecraft.class_3222.method_17355(class_3222.java:1034)
	at terramine.common.block.chests.BaseChest.method_9534(BaseChest.java:58od_26174(class_4970.java:1133)
	at net.minecraft.class_3225.method_14262(class_3225.java:343)
	at net.minecraft.class_3244.method_12046(class_3244.java:1140)
	at net.minecraft.class_2885.method_12547(class_2885.java:34)
	at net.minecraft.class_2885.method_11054(class_2885.java:8)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:12318)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:840)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Linux (amd64) version 5.15.0-89-generic
	Java Version: 17.0.9, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 3504907328 bytes (3342 MiB) / 6979321856 bytes (6656 MiB) up to 10737418240 bytes (10240 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) Gold 6348 CPU @ 2.60GHz
	Identifier: Intel64 Family 6 Model 106 Stepping 6
	Microarchitecture: Ice Lake (Server)
	Frequency (GHz): 2.60
	Number of physical packages: 2
	Number of physical CPUs: 56
	Number of logical CPUs: 112
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 573301.06
	Virtual memory used (MB): 402951.75
	Swap memory total (MB): 65536.00
	Swap memory used (MB): 9338.50
	JVM Flags: 21 total; -XX:ActiveProcessorCount=4 -Xmx10240M -Xms6656M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1
	Fabric Mods: 
		additionalstructures: Additional Structures 4.2.1
		adorabuild_structures: AdoraBuild: Structures 2.4.0
		alloy_forgery: Alloy Forgery 2.1.2+1.20
		amethyst_core: Amethyst Core 1.4.5+1.20.1
			fzzy_config: Fzzy Config 0.1.2+1.20.1
		animal_feeding_trough: Animal Feeding Trough 1.0.3+1.20.1
		aquamirae: Aquamirae 6
		archers: Archers 1.0.0+1.20.1
			structure_pool_api: Structure Pool API 1.0+1.20.1
		architectury: Architectury 9.1.12
		armorful: Armorful 2.0.2+1.20
			static-content: Static Content 1.0.1-1.16.2
				staticdata: Static Data 1.1.2
		artifacts: Artifacts 9.2.0
			expandability: ExpandAbility 9.0.0
			step-height-entity-attribute: Step Height Entity Attribute 1.2.0
		automobility: Automobility 0.4.2+1.20.1-fabric
			jsonem: JsonEM 0.2.1+1.20
		autotag-convention: AutoTag Convention 2.0.2+1.20
			autotag: AutoTag 2.0.2+1.20
		awesomedungeon: Awesome dungeon 3.2.0
		awesomedungeonend: Awesome dungeon the end 3.1.1
		awesomedungeonnether: Awesome dungeon nether 3.1.1
		awesomedungeonocean: Awesome dungeon edition ocean 3.3.0
		azurelib: AzureLib 2.0.18
		azurelibarmor: AzureLib Armor 2.0.3
		backslot: BackSlot 1.2.15
		balm-fabric: Balm 7.2.1
		barteringstation: Bartering Station 8.0.0
		bclib: BCLib 3.0.14
			wunderlib: WunderLib 1.1.5
		beautify: Beautify 1.1.0+1.20
		betterarcheology: Better Archeology 1.1.2-1.20.1
		bettercombat: Better Combat 1.8.3+1.20.1
		betterdeserttemples: YUNG's Better Desert Temples 1.20-Fabric-3.0.3
			org_reflections_reflections: reflections 0.10.2
		betterdungeons: YUNG's Better Dungeons 1.20-Fabric-4.0.3
		betterend: Better End 4.0.11
		betterendisland: YUNG's Better End Island 1.20-Fabric-2.0.4
		betterfortresses: YUNG's Better Nether Fortresses 1.20-Fabric-2.0.5
		betterjungletemples: YUNG's Better Jungle Temples 1.20-Fabric-2.0.4
		bettermineshafts: YUNG's Better Mineshafts 1.20-Fabric-4.0.4
		betternether: Better Nether 9.0.10
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.20-Fabric-3.0.4
		betterstrongholds: YUNG's Better Strongholds 1.20-Fabric-4.0.3
		bettertrims: BetterTrims 2.0.5
			mixinsquared: MixinSquared 0.1.1
		betterwitchhuts: YUNG's Better Witch Huts 1.20-Fabric-3.0.3
		biomemakeover: Biome Makeover 1.20.1-1.11.4
			taniwha: Taniwha 1.20.0-5.4.4
		bountiful: Bountiful 6.0.3+1.20.1
		c2me: Concurrent Chunk Management Engine 0.2.0+alpha.11.0
			c2me-base: Concurrent Chunk Management Engine (Base) 0.2.0+alpha.11.0
			c2me-fixes-chunkio-threading-issues: Concurrent Chunk Management Engine (Fixes/Chunk IO/Threading Issues) 0.2.0+alpha.11.0
			c2me-fixes-general-threading-issues: Concurrent Chunk Management Engine (Fixes/General/Threading Issues) 0.2.0+alpha.11.0
			c2me-fixes-worldgen-threading-issues: Concurrent Chunk Management Engine (Fixes/WorldGen/Threading Issues) 0.2.0+alpha.11.0
			c2me-fixes-worldgen-vanilla-bugs: Concurrent Chunk Management Engine (Fixes/WorldGen/Vanilla Bugs) 0.2.0+alpha.11.0
			c2me-notickvd: Concurrent Chunk Management Engine (No Tick View Distance) 0.2.0+alpha.11.0
			c2me-opts-allocs: Concurrent Chunk Management Engine (Optimizations/Memory Allocations) 0.2.0+alpha.11.0
			c2me-opts-chunk-access: Concurrent Chunk Management Engine (Optimizations/Chunk Access) 0.2.0+alpha.11.0
			c2me-opts-chunkio: Concurrent Chunk Management Engine (Optimizations/Chunk IO) 0.2.0+alpha.11.0
			c2me-opts-math: Concurrent Chunk Management Engine (Optimizations/Math) 0.2.0+alpha.11.0
			c2me-opts-scheduling: Concurrent Chunk Management Engine (Optimizations/Scheduling) 0.2.0+alpha.11.0
			c2me-opts-worldgen-general: Concurrent Chunk Management Engine (Optimizations/General WorldGen) 0.2.0+alpha.11.0
			c2me-opts-worldgen-vanilla: Concurrent Chunk Management Engine (Optimizations/Vanilla WorldGen) 0.2.0+alpha.11.0
			c2me-rewrites-chunk-serializer: Concurrent Chunk Management Engine (Rewrites/Chunk Serializer) 0.2.0+alpha.11.0
			c2me-rewrites-chunkio: Concurrent Chunk Management Engine (Rewrites/Chunk IO) 0.2.0+alpha.11.0
			c2me-server-utils: Concurrent Chunk Management Engine (Server Utils) 0.2.0+alpha.11.0
			c2me-threading-chunkio: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.0
			c2me-threading-lighting: Concurrent Chunk Management Engine (Threading/Lighting) 0.2.0+alpha.11.0
			c2me-threading-worldgen: Concurrent Chunk Management Engine (Threading/WorldGen) 0.2.0+alpha.11.0
			com_ibm_async_asyncutil: asyncutil 0.1.0
			net_objecthunter_exp4j: exp4j 0.4.8
			org_threadly_threadly: threadly 7.0
		chefsdelight: Chefs Delight 1.0.3-fabric-1.20.1
		chunkloaders: Chunk Loaders 1.2.8+a
		chunky: Chunky 1.3.92
		cinderscapes: Cinderscapes 4.0.10
			cinderscapes-common: Cinderscapes: Common 4.0.10
			cinderscapes-worldgen: Cinderscapes: World Generation 4.0.10
		cloth-config: Cloth Config v11 11.1.118
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.30
		connectedglass: Connected Glass 1.1.11
		copperhopper: Copper Hopper 0.5.1+1.20.1
		create: Create 0.5.1-d-build.1161+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.1.1127+1.20
			porting_lib_base: Porting Lib Base 2.1.1127+1.20
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.1127+1.20
				porting_lib_utility: Porting Lib Utility 2.1.1127+1.20
			porting_lib_brewing: Porting Lib Brewing 2.1.1127+1.20
			porting_lib_client_events: Porting Lib Client Events 2.1.1127+1.20
			porting_lib_entity: Porting Lib Entity 2.1.1127+1.20
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.1.1127+1.20
			porting_lib_extensions: Porting Lib Extensions 2.1.1127+1.20
			porting_lib_fake_players: Porting Lib Fake Players 2.1.1127+1.20
			porting_lib_models: Porting Lib Models 2.1.1127+1.20
				porting_lib_model_loader: Porting Lib Model Loader 2.1.1127+1.20
			porting_lib_networking: Porting Lib Networking 2.1.1127+1.20
			porting_lib_obj_loader: Porting Lib Obj Loader 2.1.1127+1.20
				porting_lib_attributes: Porting Lib Attributes 2.1.1127+1.20
			porting_lib_tags: Porting Lib Tags 3.0
				porting_lib_core: Porting Lib Core 2.1.1127+1.20
				porting_lib_gametest: Porting Lib GameTest 2.1.1127+1.20
			porting_lib_tool_actions: Porting Lib Tool Actions 2.1.1127+1.20
			porting_lib_transfer: Porting Lib Transfer 2.1.1127+1.20
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		create_structures: Create: Structures 1.1.0
		creativecore: CreativeCore 2.11.15
			net_minecraftforge_eventbus: eventbus 6.0.3
		creeperoverhaul: Creeper Overhaul 3.0.1
		cristellib: Cristel Lib 1.1.5
			blue_endless_jankson: jankson 1.2.3
		ctov: ChoiceTheorem's Overhauled Village 3.3.6
		debugify: Debugify 1.20.1+2.0
		deeperdarker: Deeper and Darker 1.2.5
			customportalapi: Custom Portal Api 0.0.1-beta64-1.20
		dualwielding: Dual Wielding 1.1.3
		dungeons_arise: When Dungeons Arise 2.1.57
		ecologics: Ecologics 2.2.0
		eldritch_end: Eldritch End 0.2.30
		elytratrims: Elytra Trims 1.4.4
			conditional-mixin: conditional mixin 0.3.2
		enchantinginfuser: Enchanting Infuser 8.0.2
		endermanoverhaul: Enderman Overhaul 1.0.3
		explorify: Explorify v1.3.0-mc1.20
		extraalchemy: Extra Alchemy 1.10.0
		fabric-api: Fabric API 0.91.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.3+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.7+29de845d77
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.3+c81d263177
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.17+kotlin.1.9.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.15.3
			mixinextras: MixinExtras 0.3.2
		farmersdelight: Farmer's Delight 1.20.1-1.4.3
		fishing101: Fishing 101 1.0.0
			polymer-core: Polymer (Core) 0.5.1+1.20.1
				polymer-networking: Polymer (Networking) 0.5.1+1.20.1
				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.5.1+1.20.1
			polymer-resource-pack: Polymer (Resource Pack) 0.5.1+1.20.1
				polymer-common: Polymer (Common) 0.5.1+1.20.1
					packet_tweaker: Packet Tweaker 0.4.0+1.19.4
			sgui: sgui 1.2.2+1.20
		flowerymooblooms: Friends&Foes - Flowery Mooblooms 2.0.0
		forgeconfigapiport: Forge Config API Port 8.0.0
		formations: Formations 1.0.2
		formationsnether: Formations Nether 1.0.3
		formationsoverworld: Formations Overworld 1.0.2
		friendsandfoes: Friends&Foes 2.0.7
		fusion: Fusion 1.1.0+c
		fzzy_core: Fzzy Core 0.3.4+1.20.1
		galosphere: Galosphere 1.20.1-1.4.1
			mm: Manningham Mills 2.3
		gazebo: Gazebos 1.1.1+1.20.1
		geckolib: GeckoLib 4 4.3.1
			com_eliotlash_mclib_mclib: mclib 20
		geode_plus: Geode+ 1.2.4
			paragon: Paragon 3.0.2
				com_moandjiezana_toml_toml4j: toml4j 0.7.2
				org_yaml_snakeyaml: snakeyaml 1.27
		go-fish: Go Fish 1.6.3+1.20.1
		graveyard: The Graveyard 2.9.1
		guardvillagers: GuardVillagers 2.0.8-1.20.1
			porting_lib_common: Porting Lib Common 2.1.1127+1.20
		hopobetterruinedportal: Hopo Better Ruined Portal 1.3.7
		hopobetterunderwaterruins: Hopo Better Underwater Ruins 1.1.3
		hybrid-aquatic: Hybrid Aquatic 1.0.1
		icarus: Icarus 1.16
		illagerinvasion: Illager Invasion 8.0.3
			extensibleenums: Extensible Enums 7.0.1
		immersive_aircraft: Immersive Aircraft 0.6.2+1.20.1
		immersive_armors: Immersive Armors 1.6.1+1.20.1
		immersive_melodies: Immersive Melodies 0.1.0+1.20.1
		imst: Immersive structures 2.1.0
		incendium: Incendium 5.3.4
		invoke: Invocations Mod 0.1.4
		itemphysiclite: ItemPhysicLite 1.6.3
		jade: Jade 11.7.0
		java: OpenJDK 64-Bit Server VM 17
		jewelry: Jewelry 1.0.0+1.20.1
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
		jobsaddon: JobsAddon 1.1.5
		kambrik: Kambrik 6.1.1+1.20.1
		levelz: LevelZ 1.4.12
		libraryferret: Library ferret 4.0.0
		libz: LibZ 1.0.3
			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.15.2
			com_fasterxml_jackson_core_jackson-core: jackson-core 2.15.2
			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.15.2
		lithium: Lithium 0.11.2
		lookinsharp: Lookin' Sharp! 1.0.2
			reach-entity-attributes: Reach Entity Attributes 2.4.1
		map_atlases: Map Atlases 2.6.0
		mavapi: More Axolotl Variants API 1.1.3
		mavm: More Axolotl Variants Mod 1.2.4
		mcwbridges: Macaw's Bridges 2.1.0
		mcwdoors: Macaw's Doors 1.1.0
		mcwfences: Macaw's Fences and Walls 1.0.7
		mcwfurnitures: Macaw's Furniture 3.2.1
		mcwlights: Macaw's Lights and Lamps 1.0.6
		mcwpaintings: Macaw's Paintings 1.0.5
		mcwpaths: Macaw's Paths and Pavings 1.0.3
		mcwroofs: Macaw's Roofs 2.2.4
		mcwtrpdoors: Macaw's Trapdoors 1.1.2
		mcwwindows: Macaw's Windows 2.2.1
		medieval_buildings: Medieval Buildings 1.0.1
		memoryleakfix: Memory Leak Fix 1.1.5
		mes: Moog's End Structures 1.1-1.20-fabric
		midnightlib: MidnightLib 1.4.1
		minecraft: Minecraft 1.20.1
		minerally: Minerally 1.20.2-1.1
		mob_captains_mr: Mob Captains 1-v2.1.2
		modernfix: ModernFix 5.12.1+mc1.20.1
		moonlight: Moonlight 1.20-2.8.80
		more_armor_trims: More Armor Trims 1.1.3-1.20.1
		moremobs: More Mobs 1.5.1+mod
		moremobvariants: More Mob Variants 1.2.2
		mozombies_wave: Mo'Zombies Wave 1.20.1-0.1.0
		mr_camps_castles_carriages: Camps. Castles. Carriages. 1.1.1
		mr_ctov_beautifycompat: CTOV - Beautify Compat 2.0
		mr_ctov_chefsdelightcompat: CTOV - Chef's delight Compat 2.0
		mr_ctov_createstructures: CTOV - Create: Structures 1.0
		mr_ctov_farmersdelightcompat: CTOV - Farmer Delight Compat 2.1
		mr_ctov_gazebocompat: CTOV - Gazebo compat 1.0
		mr_ctov_villagerspluscompat: CTOV - Villagers Plus Compat 2.0
		mr_dungeons_andtaverns: Dungeons and Taverns 3.0.3
		mr_just_anotherstructurepack: Just Another Structure Pack 1.5
		mr_qraftyfied: qraftyfied 6
		mr_reds_morestructures: Red’s More Structures 1.0.8
		mr_tidal_towns: Tidal Towns 1.2
		mr_tool_trims: Tool Trims 2.0.2+1.20
		mr_trims_expanded: Trims Expanded 1.3.0
		mr_true_ending: True Ending: Ender Dragon Overhaul 1.0.1a
		mr_vanilla_refresh: Vanilla Refresh 1.4.19a
		mvs: Moog's Voyager Structures 4.1.1-1.20-fabric
		mythic_charms: Mythic Charms 0.6.0
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
		mythicmetals: Mythic Metals 0.19.2+1.20.1
			additionalentityattributes: Additional Entity Attributes 1.4.0+1.20.0
			common-protection-api: Common Protection API 1.0.0
			mm_shedaniel: Manningham Mills (shedaniel's fork) 2.4.1
		mythicupgrades: Mythic Upgrades 2.3.2+mc1.20.1
		naturalist: Naturalist 4.0.3
		naturescompass: Nature's Compass 1.20.1-2.2.3-fabric
		necronomicon: Necronomicon 1.3.0
		netherdepthsupgrade: Nether Depths Upgrade fabric-3.1.1-1.20
		nightlights: Night Lights 1.1
		nullscape: Nullscape 1.2.4
		nyctophobia: Nyctophobia 1.9
			omega-config: OmegaConfig 1.2.2-1.18.1
		nyfsspiders: Nyf's Spiders 2.1.1
		obscure_api: Obscure API 16
		overweight_farming: Overweight Farming 1.20.1-2.0.3-fabric
		owo: oωo 0.11.2+1.20
		paraglider: Paragliders 20.1.2
		patchouli: Patchouli 1.20.1-84-FABRIC
			fiber: fiber 0.23.0-2
		pehkui: Pehkui 3.7.12+1.14.4-1.20.4
		philipsruins: Philip`s Ruins 1.20.1
		player-animator: Player Animator 1.0.2-rc1+1.20
		pottery: Pottery 1.0.1
		profundis: Profundis 1.6.1
		projectile_damage: Projectile Damage Attribute 3.2.2+1.20.1
		puffish_skills: Pufferfish's Skills 0.10.0
		puzzleslib: Puzzles Lib 8.1.12
			puzzlesaccessapi: Puzzles Access Api 8.0.7
		railways: Create: Steam 'n' Rails 1.5.1+fabric-mc1.20.1
		realisticbees: Realistic Bees 3.5
		regrowth: Regrowth 83.31.1
		reinfbarrel: Reinforced Barrels 2.4.1+1.20
			reinfcore: Reinforced Core 3.1.2+1.20
		reinfchest: Reinforced Chests 2.4.1+1.20
		reinfshulker: Reinforced Shulker Boxes 2.4.1+1.20
		repurposed_structures: Repurposed Structures 7.1.11+1.20.1-fabric
		resourcefulconfig: Resourcefulconfig 2.1.1
		resourcefullib: Resourceful Lib 2.1.20
			com_teamresourceful_bytecodecs: bytecodecs 1.0.2
			com_teamresourceful_yabn: yabn 1.0.3
		riverredux: River Redux 0.3.1
		rocks: This Rocks! 1.7.1
		roughlyenoughitems: Roughly Enough Items 12.0.684
			error_notifier: Error Notifier 1.0.9
		runes: Runes 0.9.9+1.20.1
		simple_copper_pipes: Simple Copper Pipes 1.16.1
		simply_houses: Simply Houses 1.1.4-1.20.1
		simplyskills: SimplySkills 1.0.0+1.20.1
		simplyswords: Simply Swords 1.51.5-1.20.1
		skeletonhorsespawn: Skeleton Horse Spawn 3.8
		skyvillages: Sky Villages 1.0.3.2-1.19.2-1.20.1
		sleep_tight: Sleep Tight 1.20-1.1.12
		sleepwarp: SleepWarp 2.2.0_rc1+1.20.1
		spawn: Spawn 1.0-fabric
		spell_engine: Spell Engine 0.12.4+1.20.1
		spell_power: Spell Power Attribute 0.9.19+1.20.1
		spoornpacks: SpoornPacks 5.0-1.20.1
		statement: Statement 4.2.9+1.14.4-1.20.4
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
			statement_vanilla_compatibility: Statement Vanilla Compatibility Module 1.0.1+1.16.5-1.17
		structory: Structory 1.3.4
		subterrestrial: Subterrestrial 2.2.0
		supermartijn642configlib: SuperMartijn642's Config Lib 1.1.8+a
		supermartijn642corelib: SuperMartijn642's Core Lib 1.1.16
		t_and_t: Towns and Towers 1.12
		tectonic: Tectonic 2.1.1
		terrablender: TerraBlender 3.0.1.2
			com_electronwill_night-config_core: core 3.6.7
			com_electronwill_night-config_toml: toml 3.6.7
		terralith: Terralith 2.4.11
		terramine: TerraMine 1.7.0+1.20.1
			cardinal-components-level: Cardinal Components API (world saves) 5.2.1
			cardinal-components-world: Cardinal Components API (worlds) 5.2.1
			libgui: LibGui 8.0.0+1.20
				jankson: Jankson 5.0.1+j1.2.2
				libninepatch: LibNinePatch 1.2.0
		terrestria: Terrestria 6.0.13
			terraform-dirt-api-v1: Terraform Dirt API (v1) 7.0.3
			terraform-shapes-api-v1: Terraform Shapes API (v1) 7.0.3
			terrestria-common: Terrestria: Common 6.0.13
			terrestria-worldgen: Terrestria: World Generation 6.0.13
		tiered: Tiered 1.3.0
		totw_additions: Towers of the Wild: Additions 1.3
		trashcans: Trash Cans 1.0.18
			team_reborn_energy: Energy 3.0.0
		traverse: Traverse 7.0.11
			biolith: Biolith 1.0.0-beta.1
			terraform-biome-remapper-api-v1: Terraform Biome Remapper API (v1) 7.0.3
			terraform-config-api-v1: Terraform Config API (v1) 7.0.3
			terraform-surfaces-api-v1: Terraform Surfaces API (v1) 7.0.3
			terraform-tree-api-v1: Terraform Tree API (v1) 7.0.3
			terraform-wood-api-v1: Terraform Wood API (v1) 7.0.3
			traverse-common: Traverse: Common 7.0.11
			traverse-worldgen: Traverse: World Generation 7.0.11
		trinkets: Trinkets 3.7.1
		ultris_mr: Ultris: Boss Expansion 5.6.9b
		universalenchants: Universal Enchants 8.0.0
		veinmining: Vein Mining 1.2.1+1.20.1
			spectrelib: SpectreLib 0.13.14+1.20.1
		villagernames: Villager Names 7.3
		villagersplus: Villagers Plus 3.1
		villagesandpillages: Villages&Pillages 1.0.0
		villagespawnpoint: Village Spawn Point 4.2
		wabi_sabi_structures: Wabi-Sabi Structures 2.0.0-1.20
		walllanterns: Lanterns Belong on Walls 1.6.1+1.20.1
		waystones: Waystones 14.1.3
		wetlands: Beneath the Wetlands 1.1.1
		wilderwild: Wilder Wild 2.2.3-Fabric+1.20.1
			frozenlib: FrozenLib 1.5.4-Fabric+1.20.1
		wizards: Wizards (RPG Series) 1.0.4+1.20.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.2.1+1.20
			com_twelvemonkeys_common_common-image: common-image 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-io: common-io 3.10.0-SNAPSHOT
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0-SNAPSHOT
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0-SNAPSHOT
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		yungsapi: YUNG's API 1.20-Fabric-4.0.2
			org_javassist_javassist: javassist 3.29.2-GA
		yungsbridges: YUNG's Bridges 1.20-Fabric-4.0.3
		yungsextras: YUNG's Extras 1.20-Fabric-4.0.3
		zombiehorsespawn: Zombie Horse Spawn 4.8
	Server Running: true
	Player Count: 1 / 1337; [class_3222['_pronoia_'/298, l='ServerLevel[test1]', x=-1320.18, y=68.09, z=31.12]]
	Data Packs: vanilla, fabric, jobsaddon:betterend_compat, jobsaddon:betternether_compat, resources/t_and_t_waystones_patch_1.19.2 (incompatible), spoornpacks, tectonic:terratonic
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by nihloheden** [comment]
just tried placing an empty one and opening it crashed the server aswell

**Comment by jakeb072001** [comment]
Seems to be an issue with libgui, I'll have to look into it when I have some time.

I probably just need to update libgui and change some stuff.

**Comment by nihloheden** [comment]
thank you, ill keep an eye open for an update

**Comment by jakeb072001** [comment]
Hey, so sorry about the delay, been really busy with work.

I think I have fixed this issue, before I publish the update I just wanted to send you the update first to checkout and confirm the issue is fixed.

https://www.mediafire.com/file/u30to2gqz9jlxtx/terramine-1.7.2%252B1.20.1.jar/file
