### ISSUE TITLE
Client crash with corruption biome spread

### ISSUE THREAD

**Issue by cfnnit** [jakeb072001/TerraCraft#2]
When going corruption biome While using AmbientSounds 5 or Simple Discord RPC, betterf3 etc.
It seem make client crash.

[crash-2022-06-16_12.18.23-client.txt](https://github.com/jakeb072001/TerraMine/files/8915360/crash-2022-06-16_12.18.23-client.txt)
[crash-2022-06-16_12.05.08-client.txt](https://github.com/jakeb072001/TerraMine/files/8915361/crash-2022-06-16_12.05.08-client.txt)
[crash-2022-06-15_16.21.53-client (1).txt](https://github.com/jakeb072001/TerraMine/files/8915362/crash-2022-06-15_16.21.53-client.1.txt)
[crash-2022-06-15_16.12.50-client (1).txt](https://github.com/jakeb072001/TerraMine/files/8915363/crash-2022-06-15_16.12.50-client.1.txt)

**Comment by jakeb072001** [comment]
The corruption biome spread mixin is most likely what's causing this, I may disable it temporarily in the next update until I can find a way to actually change a biome. I will test further just Incase though.

**Comment by jakeb072001** [comment]
Fixed for next update, this was done like a month ago but I forgot this issue was still open.
