### ISSUE TITLE
Ticking entity with dodge 

### ISSUE THREAD

**Issue by cfnnit** [jakeb072001/TerraCraft#3]
https://github.com/jakeb072001/TerraMine/blob/1.18.2/src/main/java/terramine/mixin/item/blackbelt/LivingEntityMixin.java
[crash-2022-06-18_17.37.12-server.txt](https://github.com/jakeb072001/TerraMine/files/8934737/crash-2022-06-18_17.37.12-server.txt)
[crash-2022-06-18_12.43.49-server.txt](https://github.com/jakeb072001/TerraMine/files/8934739/crash-2022-06-18_12.43.49-server.txt)

**Comment by jakeb072001** [comment]
Crashes with Biome Makeover, looks to be Decayed Entities. Will look into.

**Comment by jakeb072001** [comment]
Maybe fixed in latest Artifact, could you possibly try it and make sure its definitely working correctly?
https://github.com/jakeb072001/TerraMine/actions/runs/2524496105
