### ISSUE TITLE
Corruption causes world crash in 1.19

### ISSUE THREAD

**Issue by aAndrew3030** [jakeb072001/TerraCraft#4]
World is randomly crashing in 1.19. I disabled corruption in the config hoping it is a temp fix 
TerraBlender 2.0.0.113
[latest.log](https://github.com/jakeb072001/TerraMine/files/8945720/latest.log)

**Comment by jakeb072001** [comment]
I think I already fixed this in the latest Artifact: https://github.com/jakeb072001/TerraMine/actions/runs/2524948056

If it is working fine for you with that version then ill close the issue.
