### ISSUE TITLE
Dungeon bricks have no texture

### ISSUE THREAD

**Issue by UnusedCactus** [jakeb072001/TerraCraft#6]
**Describe the bug**
The green and blue dungeon bricks (normal and cracked) have no texture.

**To Reproduce**
1. Go to any blue or green dungeon
2. See error

**Game Environment**
Please provide details about the game environment, either by crash report/logs or by detailing it below.
 - Minecraft: 1.19
 - Fabric API: 58.0
 - TerraMine: 1.40
 - Trinkets: 3.40
![2022-07-31_15 59 42](https://user-images.githubusercontent.com/87100678/182043229-891eafa7-b3d8-44a9-8ad4-860862efb5f1.png)

**Comment by jakeb072001** [comment]
Oh thanks for telling me, seems GitHub decided to upload the textures with capital letters which doesn't work. Should be fixed now.
