### ISSUE TITLE
missing texture for advancements background

### ISSUE THREAD

**Issue by Surpos0** [jakeb072001/TerraCraft#7]
![2022-08-27_16 08 27](https://user-images.githubusercontent.com/110408444/187034103-e673058d-8e91-4d10-8612-1e595af8700e.png)

minecraft - 1.19
terramine - 1.5.1
fabric api - 0.58.0
terrablender - 2.0.1.125
trinkets - 3.4.0
cloth config - 8.0.75
architectury - 5.12.44

**Comment by jakeb072001** [comment]
That's odd, thought I fixed that. Code looks all good on the github, guess I'll look into it.

**Comment by jakeb072001** [comment]
Ah, I misread, I fixed the advancement screen now. I thought this was for the config screen, whoops.
